# -*- coding: utf-8 -*-
"""Final Draft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZ4wM9pJOSP-33zHqp5iVrA-FcA7DZy9
"""

def createacct():
  username = input("name")
  password = input("pass")

  file = open("account.txt", "r")
  file.write(username + " " + password + "\n")
  file.close()

def login():
  username = input("name")
  password = input("pass")

  file = open("account.txt", "r")
  for line in file:
      stored_username, stored_password = line.split()
      if username == stored_username and password == stored_password:
        print("login successful")
        return
  print("login failed")
  file.close()